---
- name: Copy and unchive files
  hosts: all
  become: yes
  become_user: "{{ become_user }}"
  tasks:
    - copy:
        src: "{{ playbook_dir }}/user_files/nginx.cfg"
        dest: /home/osboxes/nginx.cfg
        mode: '0700'
