---
- name: Reset linux account on all hosts
  hosts: all
  become: yes
  become_user: "{{ become_user }}"
  tasks:
    - user:
        name: "{{ user }}"
        update_password: always
        password: "{{ newpw|password_hash('sha512') }}"
