---
- name: Copy and unchive files
  hosts: all
  become: yes
  become_user: "{{ become_user }}"
  tasks:
    - unarchive:
        copy: yes
        src: "{{ playbook_dir }}/user_files/a_folder.xz"
        dest: /home/osboxes/
        owner: osboxes
        group: devops
        mode: '0644'
